apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: app
  name: app
spec:
  containers:
  - image: igorvit/count_connections:1.2
    name: app
    resources: {}
    env:
    - name: PYTHONUNBUFFERED
      value: '1'
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}