apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: app
  name: app
spec:
  containers:
  - image: igorvit/count_connections:1.5.7
    name: app
    resources: {}
    volumeMounts:
    - name: pvc-logs
      mountPath: /tmp/
  volumes:
    - name: pvc-logs
      persistentVolumeClaim:
        claimName: pvc-logs
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  terminationGracePeriodSeconds: 0
status: {}